#
#  Virtual host for 
#
#    domain parking.cweb.com.au
#    website parking.cweb.com.au
#
 
<VirtualHost *:80>
   Include ${WEBSITE_DIR}/etc/www.conf
</VirtualHost>

<VirtualHost *:443>
   SSLEngine on
   SSLCertificateFile ${WEBSITE_DIR}/etc/certificates/www.${WEBSITE_NAME}/cert.pem
   SSLCertificateKeyFile ${WEBSITE_DIR}/etc/certificates/www.${WEBSITE_NAME}/key.pem
   SSLCertificateChainFile ${WEBSITE_DIR}/etc/certificates/www.${WEBSITE_NAME}/cacert.pem

   Include ${WEBSITE_DIR}/etc/www.conf
</VirtualHost>
