#
#  Virtual host for 
#
#    domain parking.cweb.com.au
#    website parking.cweb.com.au
#
 
<VirtualHost *:80>
   ServerName parking.cweb.com.au
   ServerAlias www.parking.cweb.com.au 

   Include /home/www/parking.cweb.com.au/etc/www.conf
</VirtualHost>

<VirtualHost *:443>

   ServerName parking.cweb.com.au
   ServerAlias www.parking.cweb.com.au

   Include /home/www/parking.cweb.com.au/etc/www.conf

   SSLEngine on
   SSLCertificateFile /home/www/parking.cweb.com.au/etc/certificates/www.parking.cweb.com.au/cert.pem
   SSLCertificateKeyFile /home/www/parking.cweb.com.au/etc/certificates/www.parking.cweb.com.au/key.pem
   SSLCertificateChainFile /home/www/parking.cweb.com.au/etc/certificates/www.parking.cweb.com.au/cacert.pem
   Include /home/www/parking.cweb.com.au/etc/www.conf

</VirtualHost>
