   
   DocumentRoot /home/www/parking.cweb.com.au/public_html
   DirectoryIndex index.php index.html index.htm
   SetEnv TZ Australia/Sydney
   ErrorLog /home/www/parking.cweb.com.au/var/log/www_error_log
   CustomLog /home/www/parking.cweb.com.au/var/log/www_access_log combined
   php_flag magic_quotes_gpc off
   php_value include_path "/home/www/parking.cweb.com.au/lib:/usr/local/lib/php:."
   php_value auto_prepend_file "header.php"
